name: Keep App Alive

on:
  schedule:
    - cron: '0 * * * *' # Executes every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: |
          curl -I https://inventorysystem-bqvcgwvkigfchoykmmg9rb.streamlit.app/
          curl -I https://analytics-dashboard-yg4k2jgginumuyzhy4pznd.streamlit.app/
